SERVICE:
  PORT: 6000
LOG:
  # Enable or disable logging -> "true" or "false"
  ENABLE: "false"
  # Path where log files will be saved
  PATH: "./log"
  # Logging level: debug, info, warning, error, critical
  LEVEL: "debug"